# Generated by Django 5.2.8 on 2025-12-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_email_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_applied',
            field=models.BooleanField(default=False, help_text='If True, 18% GST was applied to the order'),
        ),
    ]
