# Generated by Django 5.2.8 on 2025-12-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show in the brand marquee on the home page'),
        ),
    ]
